"""Evidence Vault: structured legal / ecological metadata for archived spills + reconstructed day-by-day footprint frames."""
import math
from datetime import timedelta
from typing import List

# name → legal & ecological evidence (public sources)
VAULT = {
    "Deepwater Horizon (Macondo)": {"duration_days": 87, "max_area_km2": 149000, "ruling": "US District Court (E.D. La.) 2014 found BP grossly negligent under the Clean Water Act; 2016 consent decree.", "penalties": "US$20.8 bn settlement (largest environmental settlement in US history) + US$4 bn criminal plea (2012).", "cleanup_cost": "≈ US$14 bn response cost; total BP liabilities > US$65 bn.", "compensation": "US$5.5 bn CWA penalty, US$8.8 bn natural-resource damages, US$5.9 bn to states/localities.", "ecological": "Deepwater coral mortality, dolphin & sea-turtle die-offs, ~1,100 km oiled shoreline; multi-decade NRDA monitoring.", "sources": [{"t": "US DOJ consent decree", "u": "https://www.justice.gov/enrd/deepwater-horizon"}, {"t": "NOAA DWH NRDA", "u": "https://www.gulfspillrestoration.noaa.gov/"}]},
    "Exxon Valdez": {"duration_days": 60, "max_area_km2": 28000, "ruling": "Exxon Shipping Co. v. Baker (US Supreme Court, 2008) capped punitive damages at 1:1 to compensatory.", "penalties": "US$125 m criminal (1991 plea), US$900 m civil settlement.", "cleanup_cost": "≈ US$2.1 bn.", "compensation": "US$507.5 m punitive to ~32,000 plaintiffs after Supreme Court reduction.", "ecological": "≈250,000 seabirds, 2,800 sea otters, 300 harbour seals; herring collapse 1993; lingering subsurface oil decades later.", "sources": [{"t": "EVOS Trustee Council", "u": "https://evostc.state.ak.us/"}, {"t": "Exxon v. Baker", "u": "https://supreme.justia.com/cases/federal/us/554/471/"}]},
    "Prestige": {"duration_days": 45, "max_area_km2": 10000, "ruling": "Spanish Supreme Court 2016 convicted the master of reckless environmental crime and held the owner/insurer (London P&I) liable up to US$1 bn.", "penalties": "Master 2-year sentence; civil liability ~€1.5 bn assessed.", "cleanup_cost": "≈ €2.5 bn including fisheries losses.", "compensation": "IOPC Fund paid up to the €171.5 m CLC/Fund limit; Spain sued the classification society (ABS) in the US unsuccessfully.", "ecological": ">2,000 km of coast oiled; 115,000–230,000 seabirds estimated killed; shellfish grounds closed 6 months.", "sources": [{"t": "IOPC Funds incident page", "u": "https://iopcfunds.org/incidents/incident-map/#100-2002-190-November"}, {"t": "CEDRE Prestige", "u": "https://wwz.cedre.fr/en/Resources/Spills/Spills/Prestige"}]},
    "Erika": {"duration_days": 30, "max_area_km2": 4000, "ruling": "Cour de cassation (2012) upheld Total SA's criminal conviction and recognised 'préjudice écologique' (pure ecological damage) as compensable.", "penalties": "€375,000 fine (Total) + damages ~€200 m.", "cleanup_cost": "≈ €200 m response; economic losses ~€1 bn.", "compensation": "IOPC Fund + Total voluntary payments ≈ €200 m; landmark ecological-damage award.", "ecological": ">60,000 seabirds oiled (largest European bird kill); 400 km coast; oyster farms closed.", "sources": [{"t": "Cour de cassation 25 Sept 2012", "u": "https://www.courdecassation.fr/"}, {"t": "IOPC Funds Erika", "u": "https://iopcfunds.org/incidents/"}]},
    "Sanchi": {"duration_days": 14, "max_area_km2": 300, "ruling": "Investigation by Iran/China/Panama; no criminal ruling; flag-state MSA reports on collision liability.", "penalties": "Liability apportioned between CF Crystal and Sanchi owners (collision).", "cleanup_cost": "Limited — condensate evaporated/burned; monitoring costs.", "compensation": "Claims via Panama-flag insurers; 32 crew lost (no survivors).", "ecological": "Condensate toxicity to plankton/fish larvae; Japan Ryukyu beaches received clumps; fisheries advisories East China Sea.", "sources": [{"t": "ITOPF Sanchi", "u": "https://www.itopf.org/in-action/case-studies/sanchi-east-china-sea-2018/"}]},
    "MV Wakashio": {"duration_days": 25, "max_area_km2": 30, "ruling": "Mauritius court 2021 convicted captain & first officer (20 months) for endangering safe navigation.", "penalties": "Owner Nagashiki Shipping capped liability under LLMC; Mauritius sought ~US$34 m.", "cleanup_cost": "≈ US$34 m claimed for cleanup and rehabilitation.", "compensation": "Owner/insurer (Japan P&I) paid fishermen & tourism compensation; Japan JICA reef restoration aid.", "ecological": "Blue Bay Marine Park and Île aux Aigrettes mangroves oiled; 39 dolphins/whales stranded; VLSFO persistence in mangroves.", "sources": [{"t": "ITOPF Wakashio", "u": "https://www.itopf.org/in-action/case-studies/wakashio-mauritius-2020/"}]},
    "MT Dawn Kanchipuram – Chennai (Ennore) collision": {"duration_days": 20, "max_area_km2": 40, "ruling": "DG Shipping inquiry; Madras High Court PIL (2017) on response failures; NGT directed compensation assessment.", "penalties": "Ship-owners' P&I clubs funded cleanup; no criminal conviction reported.", "cleanup_cost": "≈ ₹ 4–5 crore reported cleanup; volunteer-driven manual removal of ~250 t sludge.", "compensation": "Fisher compensation ordered by TN government (₹ 1,000/day interim); NGT monitoring.", "ecological": "34 km Ennore–Marina coastline oiled; olive ridley nesting season impacted; fisheries losses for ~3 weeks.", "sources": [{"t": "ICG press release 2017", "u": "https://indiancoastguard.gov.in/"}, {"t": "NGT Southern Zone orders", "u": "https://www.greentribunal.gov.in/"}]},
    "Ennore / Kamarajar Port spill (Cyclone Michaung)": {"duration_days": 25, "max_area_km2": 20, "ruling": "NGT (Southern Zone) 2024 imposed interim environmental compensation on CPCL; TNPCB directions.", "penalties": "₹ 5 crore interim environmental compensation (NGT, 2024) on CPCL.", "cleanup_cost": "CPCL-funded creek cleanup with contractors; Coast Guard booms.", "compensation": "TN government relief to ~6,000 affected fisher families.", "ecological": "Ennore creek & Kosasthalaiyar mangroves, Buckingham Canal oiled; fish/crab mortality.", "sources": [{"t": "NGT SZ order (Ennore oil spill)", "u": "https://www.greentribunal.gov.in/"}]},
    "Hebei Spirit": {"duration_days": 45, "max_area_km2": 15000, "ruling": "Korean Supreme Court 2009 held Samsung Heavy Industries' tug negligent; tanker master acquitted on appeal.", "penalties": "Samsung: KRW 30 m fine; liability capped at KRW 5.6 bn under LLMC (controversial).", "cleanup_cost": "≈ US$300 m+.", "compensation": "IOPC 1992 Fund ~US$200 m + Korean special act; ~128,000 claims.", "ecological": "375 km Taean coast; aquaculture & tidal flats damaged; 1.2 M volunteers mobilised.", "sources": [{"t": "IOPC Funds Hebei Spirit", "u": "https://iopcfunds.org/incidents/"}]},
    "Amoco Cadiz": {"duration_days": 60, "max_area_km2": 5000, "ruling": "US District Court (N.D. Ill.) 1984–1992 found Amoco liable (defective steering gear, inadequate maintenance).", "penalties": "US$204 m damages (1992) to France and Brittany communes.", "cleanup_cost": "≈ FRF 500 m; largest cleanup of its era.", "compensation": "US$204 m awarded after 14 years of litigation.", "ecological": "360 km coast; 20,000 birds; oyster beds destroyed; marshes took 7+ years to recover.", "sources": [{"t": "CEDRE Amoco Cadiz", "u": "https://wwz.cedre.fr/en/Resources/Spills/Spills/Amoco-Cadiz"}]},
    "Torrey Canyon": {"duration_days": 30, "max_area_km2": 700, "ruling": "Settled 1969 (UK/France vs Barracuda Tanker Corp) after arrest of sister ship; led to CLC 1969 & Intervention Convention.", "penalties": "£3 m settlement shared UK/France.", "cleanup_cost": "≈ £2 m UK; detergents and RAF bombing.", "compensation": "£3 m settlement.", "ecological": "~15,000 seabirds; toxic detergents devastated intertidal life (recovery 10–15 years).", "sources": [{"t": "ITOPF Torrey Canyon", "u": "https://www.itopf.org/in-action/case-studies/torrey-canyon-united-kingdom-1967/"}]},
    "X-Press Pearl": {"duration_days": 40, "max_area_km2": 200, "ruling": "Sri Lanka Supreme Court 2025 ordered owner to pay US$1 bn initial compensation (fundamental-rights petitions); UK admiralty limitation proceedings ongoing.", "penalties": "US$1 bn SC order; interim US$7.85 m paid by owner (2021–22).", "cleanup_cost": "Nurdle cleanup ongoing; UNEP estimated damages US$6.4 bn.", "compensation": "Fisher relief ~LKR 1.2 bn interim; UNEP/Sri Lanka claims process.", "ecological": "1,680 t plastic nurdles (worst maritime plastic spill), 400+ turtles and 50 dolphins dead; Negombo lagoon fisheries closed.", "sources": [{"t": "UNEP X-Press Pearl report", "u": "https://www.unep.org/resources/report/x-press-pearl-maritime-disaster-sri-lanka"}, {"t": "Sri Lanka Supreme Court judgment 2025", "u": "https://www.supremecourt.lk/"}]},
}


def reconstruct_frames(entry: dict) -> List[dict]:
    """Day-by-day RECONSTRUCTED footprint: area grows ∝ √t to max_area_km2 then weathers/disperses. Not a satellite record."""
    v = VAULT.get(entry["name"], {})
    days = int(v.get("duration_days") or max(3, min(60, round((entry.get("volume_tonnes") or 100) ** 0.33))))
    a_max = float(v.get("max_area_km2") or max(2.0, (entry.get("volume_tonnes") or 100) * 0.05))
    frames = []
    for d in range(1, days + 1):
        frac = math.sqrt(min(1.0, d / (days * 0.6))) * (1.0 if d <= days * 0.6 else max(0.15, 1 - (d - days * 0.6) / (days * 0.5)))
        area = a_max * frac
        r_km = math.sqrt(area / math.pi)
        frames.append({"day": d, "date": entry["date"] + timedelta(days=d - 1), "area_km2": round(area, 1), "radius_km": round(r_km, 2), "elongation": 2.0 + 0.05 * d})
    return frames
